version: '3'
services:
  fritzbox-prometheus-exporter:
    image: fritzbox_exporter:latest
    # for dns issues like "dial tcp: lookup fritz.box on 127.0.0.11:53: no such host"
    # uncomment and fill the following line:
    # dns: YOUR_FRITZBOX_IP
    ports:
      - "9042:9042"
    #expose:
    #  - "9042"
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true # default
